[package]
name = "smtp-codec"
version = "0.1.0"
authors = ["Damian Poddebniak <poddebniak@fh-muenster.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5.1"
abnf-core = "0.3.0"